

name: Python application (windows compilation)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install wine and python
      run: |
          sudo apt-get install wine
          wine msiexec /i python-3.11.2.msi /L*v log.txt
    - name: Install Pip on wine
      run: |
           cd ~/.wine/drive_c/Python311
           wine python.exe Scripts/pip install --upgrade pip 
    - name: Install requirements
      run: |
           wine python.exe Scripts/pip install --upgrade pip 
           wine python.exe Scripts/pip install -r requirements.txt
           wine python.exe Scripts/pip install pefile pyinstaller
           wine python.exe Scripts/pip install pyinstaller
    - name: Compile
      run: |
        wine python.exe Scripts/pyinstaller main.spec
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        # Artifact name
        name: gaim
        # A file, directory or wildcard pattern that describes what to upload
        path: dist
        # The desired behavior if no files are found using the provided path.
